### ISSUE TITLE
Fails to parse "---" header in yaml files

### ISSUE THREAD

**Issue by jrfondren** [openpeep/nyml#7]
https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file

If someone's reading YAML files, it's because something else is choosing to emit YAML, and when that something else is Perl it adds a header by default:

```
% perl -MYAML=Dump -le 'print Dump({some => "content"})'
---
some: content
```

sample.yaml:

```yaml
---
name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -Y
      - run: nim --threads:on c -r src/tim.nim
      - run: nimble test
```

program.nim:

```nim
import nyml
echo readFile("sample.yaml").yaml.toJson
```

Output with sample.yaml:

```
/Users/jfondren/nim/bug/nymlbug/src/nymlbug.nim(3) nymlbug
/Users/jfondren/.nimble/pkgs/nyml-0.1.3/nyml.nim(38) toJson
/Users/jfondren/nim/nim-1.6.12/lib/pure/json.nim(1035) parseJson
/Users/jfondren/nim/nim-1.6.12/lib/pure/json.nim(952) parseJson
/Users/jfondren/nim/nim-1.6.12/lib/pure/parsejson.nim(519) eat
/Users/jfondren/nim/nim-1.6.12/lib/pure/parsejson.nim(515) raiseParseErr
Error: unhandled exception: input(1, 3) Error: EOF expected [JsonParsingError]
```

Output with the same file absent the --- line:

```
(contents: {"name":"test","on":{"push":{"paths-ignore":["LICENSE","README.*"]},"pull_request":{"paths-ignore":["LICENSE","README.*"]}},"jobs":{"test":{"runs-on":"ubuntu-latest","strategy":{"matrix":{"nim-version":["stable"]}},"steps":[{"uses":"actions/checkout@v2"},{"uses":"jiro4989/setup-nim-action@v1","with":{"nim-version":"${{ matrix.nim-version }}","repo-token":"${{ secrets.GITHUB_TOKEN }}"}},{"run":"nimble install -Y"},{"run":"nim --threadson c -r src/tim.nim"},{"run":"nimble test"}]}}}, rules: @[], hasErrors: false, errors: @[])
```

Since I have files that I know have the --- header and are otherwise extremely simple, I have this workaround:

```nim
import nyml, std/[strutils, sugar]
echo readFile("sample.yaml").dup(removePrefix("---\n")).yaml.toJson
```

Or without sugar:

```nim
import nyml, std/strutils
var contents = readFile("sample.yaml")
contents.removePrefix("---\n")
echo contents.yaml.toJson
```
